"""
02_etl_load.py — Loan Portfolio Analytics
==========================================
Loads the six star-schema CSVs (generated by build_star_schema.py) into MySQL.

Usage:
    pip install pandas mysql-connector-python
    python 02_etl_load.py --host localhost --user root --password yourpw

If you run the companion 03_views.sql / 04_analysis_queries.sql in MySQL Workbench
you do NOT need this script — it is only needed to load data into MySQL.
"""

import argparse
import pandas as pd
import mysql.connector
from mysql.connector import Error
import os
import sys

DATA_DIR = os.path.join(os.path.dirname(__file__), 'powerbi', 'data')

LOAD_ORDER = [
    ('dim_date',      'dim_date.csv'),
    ('dim_grade',     'dim_grade.csv'),
    ('dim_purpose',   'dim_purpose.csv'),
    ('dim_ownership', 'dim_ownership.csv'),
    ('dim_status',    'dim_status.csv'),
    ('fact_loans',    'fact_loans.csv'),
]

def get_connection(host, user, password, port=3306):
    return mysql.connector.connect(
        host=host, user=user, password=password,
        database='loan_portfolio', port=port,
        autocommit=False
    )

def load_table(cursor, table_name, df):
    cols   = list(df.columns)
    ph     = ', '.join(['%s'] * len(cols))
    col_s  = ', '.join(f'`{c}`' for c in cols)
    sql    = f"INSERT IGNORE INTO `{table_name}` ({col_s}) VALUES ({ph})"
    rows   = [tuple(None if pd.isna(v) else v for v in row) for row in df.itertuples(index=False)]
    cursor.executemany(sql, rows)
    return len(rows)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--host',     default='localhost')
    parser.add_argument('--user',     default='root')
    parser.add_argument('--password', default='')
    parser.add_argument('--port',     default=3306, type=int)
    args = parser.parse_args()

    try:
        con = get_connection(args.host, args.user, args.password, args.port)
        cursor = con.cursor()
        print(f"Connected to MySQL on {args.host}:{args.port}\n")

        # Disable FK checks for bulk load
        cursor.execute("SET FOREIGN_KEY_CHECKS = 0;")

        for table, csv_file in LOAD_ORDER:
            path = os.path.join(DATA_DIR, csv_file)
            df   = pd.read_csv(path)
            cursor.execute(f"DELETE FROM `{table}`;")
            n    = load_table(cursor, table, df)
            con.commit()
            print(f"  ✓  {table:<20}  {n:>5} rows loaded from {csv_file}")

        cursor.execute("SET FOREIGN_KEY_CHECKS = 1;")
        con.commit()

        # Quick row-count verification
        print("\nRow counts in DB:")
        for table, _ in LOAD_ORDER:
            cursor.execute(f"SELECT COUNT(*) FROM `{table}`;")
            print(f"  {table:<20}  {cursor.fetchone()[0]:>5}")

        # KPI sanity check
        cursor.execute("""
            SELECT
                COUNT(*)                                        AS total_loans,
                SUM(s.is_risk)                                  AS at_risk,
                ROUND(SUM(f.loan_amnt), 0)                      AS total_originated,
                ROUND(SUM(f.total_rec_int), 2)                  AS interest_earned
            FROM fact_loans f
            JOIN dim_status s ON f.status_key = s.status_key;
        """)
        row = cursor.fetchone()
        print(f"\nKPI sanity check:")
        print(f"  Total loans      : {row[0]:>7,}")
        print(f"  At-risk loans    : {row[1]:>7,}  ({row[1]/row[0]*100:.1f}%)")
        print(f"  Total originated : ${row[2]:>12,.0f}")
        print(f"  Interest earned  : ${row[3]:>12,.2f}")
        print("\nETL complete — all checks passed.")

    except Error as e:
        print(f"MySQL Error: {e}")
        sys.exit(1)
    finally:
        if 'cursor' in dir(): cursor.close()
        if 'con'    in dir() and con.is_connected(): con.close()

if __name__ == '__main__':
    main()
